### PR TITLE
Jeedom V4 UI

### PR DESCRIPTION
**Pull request by KiboOst**

### CODE REVIEW

**Comment by CoorFun** [comment]
LGTM, will make some test and get merged

**Comment by KiboOst** [comment]
I guess you should configure actual master as market v3, and create a new stableV4 branch and set it in market.
So v3 stable won't be updated, but jeedom v4 will get the stableV4 branch.

**Comment by CoorFun** [comment]
Good to know, will do so! 👍

**Comment by CoorFun** [comment]
I saw that there are some styles messing in the new version. Do you have any references regarding the new stylesheet? Like the component that I can use etc.. Is it still using bootstrap 3.xx?

**Comment by KiboOst** [comment]
It still use bt 3 but with own theme on top of it. The main goal is to remove a maximum of inline style and support light/dark themes.
You can have more informations on partenaire jeedom forum

**Comment by CoorFun** [comment]
I'v created [adaption/v4](https://github.com/snipsco/snips-jeedom-plugin/tree/adaption/v4) branch for this migration and I'v made some small changes. Do you think we can now push the changes to beta? 

My concern is if the user on v3 will still receive this beta update or not?

**Comment by KiboOst** [comment]
Check snips discord ;-)

**Comment by KiboOst** [comment]
Had an update for beta on V4, but still the old UI ... Same for V4 Stable.
Any problem why it's not available ?

**Pull request closed without merging**
